require: rubocop-rspec

AllCops:
  Exclude:
    - betagouvbot.gemspec
    - Guardfile
    - spec/spec_helper.rb
    - vendor/**/*
    - tmp/**/*

  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 90

RSpec/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  Enabled: true

Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Enabled: true

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Max: 4

RSpec/ExampleLength:
  Max: 7

RSpec/NestedGroups:
  Max: 4
